# Generated by Django 5.0.7 on 2024-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.PositiveIntegerField(blank=True)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "CSE"),
                            ("IT", "IT"),
                            ("ECE", "ECE"),
                            ("MECH", "MECH"),
                            ("CIVIL", "CIVIL"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
