# Generated by Django 5.0.7 on 2024-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_manage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, upload_to="student_photos"),
        ),
    ]
