# Generated by Django 5.0.7 on 2024-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_manage", "0002_student_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="photo"
            ),
        ),
    ]
