# Generated by Django 5.0.7 on 2024-07-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_manage", "0003_alter_student_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="photo",
        ),
    ]
